# -*- coding: utf-8 -*-
"""extract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTNY7LLJIjDPk4AbWaCwYIF6c_lyR0f_
"""

import requests
from bs4 import BeautifulSoup

url = "https://my-h5news.app.xinhuanet.com/h5/specialTopic/indexPc.html?articleId=024a90db17da4691868e51bd10420f78"

response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

#print(soup)

full_text = soup.find_all("p")
#print(full_text)
for txt in soup.find_all("p"):
  result = txt.get_text()
  print(result)